---FIND THE RUNNING TOTAL OF SALES FOR EACH MONTH
WITH CTE_MONTLYSUMMARY AS
(
SELECT 
DATETRUNC(MONTH,OrderDate) ORDERMONTH,
SUM(SALES) TOTALSALES,
COUNT(OrderID) TOTALORDERS,
SUM(QUANTITY) TOTALQUANTITY
FROM SALES.Orders
GROUP BY DATETRUNC(MONTH,OrderDate)
) 
SELECT
ORDERMONTH,
TOTALSALES,
SUM(TOTALSALES) OVER(ORDER BY ORDERMONTH) AS RUNNINGTOTAL
FROM CTE_MONTLYSUMMARY
---PROVIDE EVERYTHING FROM ORDERS,PRODUCT,CUSTOMER,EMPLOYEES
CREATE VIEW SALES.V_ALLDETAILS AS (
SELECT
O.ORDERID,
O.ORDERDATE,
O.Quantity,
P.Product,
P.Category,
C.CustomerID,
C.FirstName +' '+COALESCE( C.LastName,' ') AS NAMES,
C.Score,
E.Department,
E.BirthDate,
E.Salary,
E.EmployeeID,
E.FIRSTNAME AS EMPLOYEEFIRSTNAME,
CASE WHEN E.Gender='M' THEN 'MALE'
     WHEN E.GENDER='F' THEN 'FEMALE'
     ELSE 'NULL'
     END 'E.GENDERNAME'
FROM SALES.Orders O
LEFT JOIN SALES.Products P
ON P.ProductID=O.ProductID
LEFT JOIN SALES.Customers C
ON C.CustomerID=O.CustomerID
LEFT JOIN SALES.Employees E
ON E.EmployeeID=O.CustomerID
)
SELECT * FROM SALES.V_ALLDETAILS
---PROVIDE A VIEW FOR EU SALES TEAM THAT COMBINE DETAIL FROM ALL TABLE AND EXCLUDE DATA RELATED TO USA
CREATE VIEW SALES.ALLDETAISUSA AS (
SELECT
O.ORDERID,
O.ORDERDATE,
O.Quantity,
O.Sales,
P.Product,
P.Category,
C.CustomerID,
C.FirstName +' '+COALESCE( C.LastName,' ') AS NAMES,
C.Score,
E.Department,
E.BirthDate,
E.Salary,
E.EmployeeID,
E.FIRSTNAME AS EMPLOYEEFIRSTNAME,
CASE WHEN E.Gender='M' THEN 'MALE'
     WHEN E.GENDER='F' THEN 'FEMALE'
     ELSE 'NULL'
     END 'E.GENDERNAME'
FROM SALES.Orders O
LEFT JOIN SALES.Products P
ON P.ProductID=O.ProductID
LEFT JOIN SALES.Customers C
ON C.CustomerID=O.CustomerID
LEFT JOIN SALES.Employees E
ON E.EmployeeID=O.CustomerID
WHERE C.Country !='USA'
)
SELECT * FROM SALES.ALLDETAISUSA